// AUTO-GENERATED by scripts/import-website-products.mjs — do not hand-edit.

import type { Product } from "./products";

export const importedWebsiteProducts = [
  {
    "id": 100,
    "name": "Anarkalis · product1 · Shivaanya Collection",
    "price": 1399,
    "originalPrice": 1532,
    "imageUrl": "/media/catalog/anarkalis/anarkalis-product1/img001.jpg",
    "videoUrl": "/media/catalog/anarkalis/anarkalis-product1/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/anarkalis/anarkalis-product1/img001.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img002.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img003.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img004.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img005.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img006.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img007.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img008.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img009.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img010.jpg",
      "/media/catalog/anarkalis/anarkalis-product1/img011.jpg"
    ],
    "categoryName": "Anarkalis",
    "description": "• You gonna love elegance with Modern touch ,Here we Presenting Exclusive Design\n• Anarkali: Anarkali embroidery work butta georgette Anarkali suit with huge flair, anarkali length 49+\n• Pant: Buttersilk pant fully stitched\n• Dupatta Printed Georgette 2mtr Dupatta with lace border!\n• Fully stitched\n• Available Size 34,36,38,40,42 ( margin avl for 44)\n• Same as shown in video\n• Ready stock !!\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Lightweight breathable suit textiles with ornate detailing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.5,
    "reviewCount": 288,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 101,
    "name": "Anarkalis · product4 · Shivaanya Collection",
    "price": 2099,
    "originalPrice": 2274,
    "imageUrl": "/media/catalog/anarkalis/anarkalis-product4/img001.webp",
    "videoUrl": "/media/catalog/anarkalis/anarkalis-product4/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/anarkalis/anarkalis-product4/img001.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img002.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img003.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img004.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img005.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img006.webp",
      "/media/catalog/anarkalis/anarkalis-product4/img007.webp"
    ],
    "categoryName": "Anarkalis",
    "description": "• Shivaanya Collection Presenting New Đěsigner Anarkali Suit In New Fancy Style\n• Anarkali fabric: Heavy Blooming Georgette And bits Embroidery Work( Fully Sleevs )\n• Anarkali flair: 4 mtr\n• Anarkali inner: Micro\n• Anarkali length: 46-47’ Inch\n• Dupatta fabric: Heavy Blooming Georgette With fancy lees..(dupatta size 2.30 Meter) md\n• Plazo: Heavy Blooming Georgette..\n• ( Fully Stitched )\n• Anarkali size: S(36),M(38),L(40),XL(42) XXL(44)+Margin ( Fully Stitched )\n• Weight : 1kg\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Lightweight breathable suit textiles with ornate detailing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.7,
    "reviewCount": 163,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 102,
    "name": "Lehengas · product1 · Shivaanya Collection",
    "price": 0,
    "imageUrl": "/media/catalog/lehengas/lehengas-product1/img001.webp",
    "images": [
      "/media/catalog/lehengas/lehengas-product1/img001.webp",
      "/media/catalog/lehengas/lehengas-product1/img002.webp",
      "/media/catalog/lehengas/lehengas-product1/img003.webp",
      "/media/catalog/lehengas/lehengas-product1/img004.webp",
      "/media/catalog/lehengas/lehengas-product1/img005.webp",
      "/media/catalog/lehengas/lehengas-product1/img006.webp",
      "/media/catalog/lehengas/lehengas-product1/img007.webp",
      "/media/catalog/lehengas/lehengas-product1/img008.webp",
      "/media/catalog/lehengas/lehengas-product1/img009.webp",
      "/media/catalog/lehengas/lehengas-product1/img010.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• Real modelling Product\n• Fabric: Pure Vichitra\n• Work: Embroidery cording Sequence Work with thread work\n• Inner: Micro Cotton\n• Size: M upto L margin\n• XL upto 2xl margin\n• (Fully Stitched)\n• Work: Heavy cording Embroidery Sequence with Thared Work\n• Flair: 3.50 Meter\n• Size: 2.30 Meter\n• Coluer: 2 two\n• Attache Sleeve\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.8,
    "reviewCount": 153,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 103,
    "name": "Lehengas · product10 · Shivaanya Collection",
    "price": 1799,
    "originalPrice": 1956,
    "imageUrl": "/media/catalog/lehengas/lehengas-product10/img001.webp",
    "images": [
      "/media/catalog/lehengas/lehengas-product10/img001.webp",
      "/media/catalog/lehengas/lehengas-product10/img002.webp",
      "/media/catalog/lehengas/lehengas-product10/img003.webp",
      "/media/catalog/lehengas/lehengas-product10/img004.webp",
      "/media/catalog/lehengas/lehengas-product10/img005.webp",
      "/media/catalog/lehengas/lehengas-product10/img006.webp",
      "/media/catalog/lehengas/lehengas-product10/img007.webp",
      "/media/catalog/lehengas/lehengas-product10/img008.webp",
      "/media/catalog/lehengas/lehengas-product10/img009.webp",
      "/media/catalog/lehengas/lehengas-product10/img010.webp",
      "/media/catalog/lehengas/lehengas-product10/img011.webp",
      "/media/catalog/lehengas/lehengas-product10/img012.webp",
      "/media/catalog/lehengas/lehengas-product10/img013.webp",
      "/media/catalog/lehengas/lehengas-product10/img014.webp",
      "/media/catalog/lehengas/lehengas-product10/img015.webp",
      "/media/catalog/lehengas/lehengas-product10/img016.webp",
      "/media/catalog/lehengas/lehengas-product10/img017.webp",
      "/media/catalog/lehengas/lehengas-product10/img018.webp",
      "/media/catalog/lehengas/lehengas-product10/img019.webp",
      "/media/catalog/lehengas/lehengas-product10/img020.webp",
      "/media/catalog/lehengas/lehengas-product10/img021.webp",
      "/media/catalog/lehengas/lehengas-product10/img022.webp",
      "/media/catalog/lehengas/lehengas-product10/img023.webp",
      "/media/catalog/lehengas/lehengas-product10/img024.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Chinon\n• Work: Embroidery Thread and Sequence Work\n• Inner: Micro Cotton\n• Size: M Upto L Margin\n• Xl Upto Xxl Margin\n• (Fully Stitched)\n• Flair: 5 Meter with Cancan\n• Work: Heavy Thread and Sequence Work\n• Weight: 1.2kg\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.6,
    "reviewCount": 219,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 104,
    "name": "Lehengas · product11 · Shivaanya Collection",
    "price": 1869,
    "originalPrice": 2030,
    "imageUrl": "/media/catalog/lehengas/lehengas-product11/img001.jpg",
    "videoUrl": "/media/catalog/lehengas/lehengas-product11/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product11/img001.jpg",
      "/media/catalog/lehengas/lehengas-product11/img002.jpg",
      "/media/catalog/lehengas/lehengas-product11/img003.jpg",
      "/media/catalog/lehengas/lehengas-product11/img004.jpg",
      "/media/catalog/lehengas/lehengas-product11/img005.jpg",
      "/media/catalog/lehengas/lehengas-product11/img006.jpg",
      "/media/catalog/lehengas/lehengas-product11/img007.jpg"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Vichitra Silk\n• Work: Heavy Embroidery Thread & Sequence Work\n• Inner: Micro Cotton\n• Size: M upto L margin\n• XL upto 2xl margin\n• (Fully Stitched)\n• Flair: 3.50 Meter\n• Attach canvas patta\n• Size: 2.30 Meter\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.8,
    "reviewCount": 298,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 105,
    "name": "Lehengas · product2 · Shivaanya Collection",
    "price": 1480,
    "originalPrice": 1618,
    "imageUrl": "/media/catalog/lehengas/lehengas-product2/img001.webp",
    "videoUrl": "/media/catalog/lehengas/lehengas-product2/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product2/img001.webp",
      "/media/catalog/lehengas/lehengas-product2/img002.webp",
      "/media/catalog/lehengas/lehengas-product2/img003.webp",
      "/media/catalog/lehengas/lehengas-product2/img004.webp",
      "/media/catalog/lehengas/lehengas-product2/img005.webp",
      "/media/catalog/lehengas/lehengas-product2/img006.webp",
      "/media/catalog/lehengas/lehengas-product2/img007.webp",
      "/media/catalog/lehengas/lehengas-product2/img008.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• Lehenga Choli\n• When the outfit speaks royalty\n• You just show up and glow\n• Catalogue: GAURI\n• Lehenga (Stitched)\n• Lehenga fabric: Tasar Silk\n• Lehenga work: Bandhej Print With Gotta Patti Lace Touch Up\n• Lehenga waist: Support Up To 42\n• Lehenga closer: Drawstring With Zip\n• Stitching: Stitched With Canvas And Full Inner\n• Flair: 4 Meter\n• Inner: Micro Crepe\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.6,
    "reviewCount": 74,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 106,
    "name": "Lehengas · product3 · Shivaanya Collection",
    "price": 1450,
    "originalPrice": 1586,
    "imageUrl": "/media/catalog/lehengas/lehengas-product3/img001.webp",
    "images": [
      "/media/catalog/lehengas/lehengas-product3/img001.webp",
      "/media/catalog/lehengas/lehengas-product3/img002.webp",
      "/media/catalog/lehengas/lehengas-product3/img003.webp",
      "/media/catalog/lehengas/lehengas-product3/img004.webp",
      "/media/catalog/lehengas/lehengas-product3/img005.webp",
      "/media/catalog/lehengas/lehengas-product3/img006.webp",
      "/media/catalog/lehengas/lehengas-product3/img007.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• PREMIUM READYMADE LEHENGA CHOLI COLLECTIONS\n• Lehengacholi\n• Lehenga: - (Full-Stitched)\n• 🏻 FABRIC :- Pure Simmer Vichitra\n• 🏻 LENGTH :- 42 INCH\n• 🏻 WAIST :- 42 INCH\n• 🏻 FLAIR :- 3.5 MTR\n• 🏻 LINING :- Cotton (Full Inner Top To Bottom)\n• 🏻 CLOSURE :- Chain Attached & With hexagon Tussels Latkan\n• 🏻 STITCHING :- Kali Pattern & Stitch with Canvas patta\n• Blouse: (Full-Stitched)\n• 🏻 FABRIC & WORK :- Position jequard\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.8,
    "reviewCount": 255,
    "isNew": false,
    "isFeatured": true,
    "isBestseller": false
  },
  {
    "id": 107,
    "name": "Lehengas · product4 · Shivaanya Collection",
    "price": 2850,
    "originalPrice": 3070,
    "imageUrl": "/media/catalog/lehengas/lehengas-product4/img001.jpg",
    "videoUrl": "/media/catalog/lehengas/lehengas-product4/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product4/img001.jpg",
      "/media/catalog/lehengas/lehengas-product4/img002.jpg",
      "/media/catalog/lehengas/lehengas-product4/img003.jpg",
      "/media/catalog/lehengas/lehengas-product4/img004.jpg",
      "/media/catalog/lehengas/lehengas-product4/img005.jpg",
      "/media/catalog/lehengas/lehengas-product4/img006.jpg",
      "/media/catalog/lehengas/lehengas-product4/img007.jpg",
      "/media/catalog/lehengas/lehengas-product4/img008.jpg",
      "/media/catalog/lehengas/lehengas-product4/img009.jpg",
      "/media/catalog/lehengas/lehengas-product4/img010.jpg"
    ],
    "categoryName": "Lehengas",
    "description": "• Exceptional Quality with Can-Can and Canvas Layers\n• A Perfect Fusion of Glamour and Comfort\n• Lehenga fabric: Fox Georgette\n• Lehenga work: Embroidery Sequins Work With Cancan & Canvas Patta\n• Lehanga flare: 4 Meter Flared\n• Lehenga type: Semi stitched\n• Lehenga Length- 42\n• Lehenga size: Upto 44\n• Blouse work: Sequins Embroidery work\n• Blosue type: 1 Meter unstitched\n• Dupatta Details\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.5,
    "reviewCount": 288,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 108,
    "name": "Lehengas · product5 · Shivaanya Collection",
    "price": 2149,
    "originalPrice": 2327,
    "imageUrl": "/media/catalog/lehengas/lehengas-product5/img001.webp",
    "images": [
      "/media/catalog/lehengas/lehengas-product5/img001.webp",
      "/media/catalog/lehengas/lehengas-product5/img002.webp",
      "/media/catalog/lehengas/lehengas-product5/img003.webp",
      "/media/catalog/lehengas/lehengas-product5/img004.webp",
      "/media/catalog/lehengas/lehengas-product5/img005.webp",
      "/media/catalog/lehengas/lehengas-product5/img006.webp",
      "/media/catalog/lehengas/lehengas-product5/img007.webp",
      "/media/catalog/lehengas/lehengas-product5/img008.webp",
      "/media/catalog/lehengas/lehengas-product5/img009.webp",
      "/media/catalog/lehengas/lehengas-product5/img010.webp",
      "/media/catalog/lehengas/lehengas-product5/img011.webp",
      "/media/catalog/lehengas/lehengas-product5/img012.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Jecard silk\n• Fancy motiwork less\n• ( Unstitched)\n• Fabric: Pure simar silk\n• Inner: Micro Cotton\n• Flair: 4 Meter\n• Fabric: Jecard soft Silk\n• Fancy Lakhan and piping\n• Weight: 1.5kg\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.7,
    "reviewCount": 209,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 109,
    "name": "Lehengas · product6 · Shivaanya Collection",
    "price": 1499,
    "originalPrice": 1638,
    "imageUrl": "/media/catalog/lehengas/lehengas-product6/img001.webp",
    "videoUrl": "/media/catalog/lehengas/lehengas-product6/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product6/img001.webp",
      "/media/catalog/lehengas/lehengas-product6/img002.webp",
      "/media/catalog/lehengas/lehengas-product6/img003.webp",
      "/media/catalog/lehengas/lehengas-product6/img004.webp",
      "/media/catalog/lehengas/lehengas-product6/img005.webp",
      "/media/catalog/lehengas/lehengas-product6/img006.webp",
      "/media/catalog/lehengas/lehengas-product6/img007.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• With Ri8 Fashion Every women would be FLAME\n• You gonna love elegance with Modern touch\n• Top: Blazer Style Embroidery Sequins work top of Soft Butterfly Net fully stitched\n• Size: 34,36,38,40,42 ( margin given)\n• Lehnga: Pure Georgette 8 mtr flair lehnga\n• Same as shown in video\n• Fully stitched\n• Ready stock !!\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.5,
    "reviewCount": 130,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 110,
    "name": "Lehengas · product7 · Shivaanya Collection",
    "price": 2499,
    "originalPrice": 2698,
    "imageUrl": "/media/catalog/lehengas/lehengas-product7/img001.jpg",
    "videoUrl": "/media/catalog/lehengas/lehengas-product7/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product7/img001.jpg",
      "/media/catalog/lehengas/lehengas-product7/img002.jpg",
      "/media/catalog/lehengas/lehengas-product7/img003.jpg",
      "/media/catalog/lehengas/lehengas-product7/img004.jpg",
      "/media/catalog/lehengas/lehengas-product7/img005.jpg",
      "/media/catalog/lehengas/lehengas-product7/img006.jpg",
      "/media/catalog/lehengas/lehengas-product7/img007.jpg",
      "/media/catalog/lehengas/lehengas-product7/img008.jpg",
      "/media/catalog/lehengas/lehengas-product7/img009.jpg"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Fox Georgette\n• Work: Heavy Embroidery Coding Sequence Work\n• Inner: Micro Cotton\n• Size: M Upto L Margin\n• Xl Upto Xxl Margin\n• (Fully Stitched)\n• Flair: 4.50 Meter\n• Weight: 1.5 Kg\n• Work: Heavy Thread and Sequence Work\n• Size: 2.30 Meter\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.8,
    "reviewCount": 51,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": true
  },
  {
    "id": 111,
    "name": "Lehengas · product8 · Shivaanya Collection",
    "price": 1969,
    "originalPrice": 2136,
    "imageUrl": "/media/catalog/lehengas/lehengas-product8/img001.jpg",
    "videoUrl": "/media/catalog/lehengas/lehengas-product8/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product8/img001.jpg",
      "/media/catalog/lehengas/lehengas-product8/img002.jpg",
      "/media/catalog/lehengas/lehengas-product8/img003.jpg",
      "/media/catalog/lehengas/lehengas-product8/img004.jpg",
      "/media/catalog/lehengas/lehengas-product8/img005.jpg",
      "/media/catalog/lehengas/lehengas-product8/img006.jpg",
      "/media/catalog/lehengas/lehengas-product8/img007.jpg",
      "/media/catalog/lehengas/lehengas-product8/img008.jpg"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Heavy Fox Georgette\n• Work: Heavy Embroidery sequence Work\n• Inner: Heavy Micro Cotton\n• Size: M upto L margin\n• XL upto 2xl margin\n• (Fully Stitched)\n• Flair: 3.5 Meter\n• Canvas Patta\n• Weight:- 1 Kg\n• Premium Quality\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.7,
    "reviewCount": 120,
    "isNew": false,
    "isFeatured": true,
    "isBestseller": true
  },
  {
    "id": 112,
    "name": "Lehengas · product9 · Shivaanya Collection",
    "price": 1799,
    "originalPrice": 1956,
    "imageUrl": "/media/catalog/lehengas/lehengas-product9/img001.webp",
    "videoUrl": "/media/catalog/lehengas/lehengas-product9/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-product9/img001.webp",
      "/media/catalog/lehengas/lehengas-product9/img002.webp",
      "/media/catalog/lehengas/lehengas-product9/img003.webp",
      "/media/catalog/lehengas/lehengas-product9/img004.webp",
      "/media/catalog/lehengas/lehengas-product9/img005.webp",
      "/media/catalog/lehengas/lehengas-product9/img006.webp",
      "/media/catalog/lehengas/lehengas-product9/img007.webp",
      "/media/catalog/lehengas/lehengas-product9/img008.webp",
      "/media/catalog/lehengas/lehengas-product9/img009.webp",
      "/media/catalog/lehengas/lehengas-product9/img010.webp",
      "/media/catalog/lehengas/lehengas-product9/img011.webp",
      "/media/catalog/lehengas/lehengas-product9/img012.webp",
      "/media/catalog/lehengas/lehengas-product9/img013.webp",
      "/media/catalog/lehengas/lehengas-product9/img014.webp"
    ],
    "categoryName": "Lehengas",
    "description": "• Fabric: Chinon\n• Work: Embroidery Thread and Sequence Work\n• Inner: Micro Cotton\n• Size: M Upto L Margin\n• Xl Upto Xxl Margin\n• (Fully Stitched)\n• Flair: 5 Meter with Cancan\n• Work: Heavy Thread and Sequence Work\n• Weight: 1.2kg\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.5,
    "reviewCount": 41,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 113,
    "name": "Code 172 · Lehengas · Shivaanya Collection",
    "price": 1849,
    "originalPrice": 2009,
    "imageUrl": "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img001.jpeg",
    "videoUrl": "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img001.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img002.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img003.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img004.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img005.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img006.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img007.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img008.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img009.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img010.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img011.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img012.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img013.jpeg",
      "/media/catalog/lehengas/lehengas-ram-172-price-1849-20260318t201013z-1-001-ram-172-price-1849/img014.jpeg"
    ],
    "categoryName": "Lehengas",
    "description": "• Product code: Ram-172\n• Real Medeling Product\n• Fabric: Pure Vichitra\n• Work: Heavy embroidery Thared Work\n• Inner: Micro Cotton\n• Size: M upto L margin\n• XL upto 2xl margin\n• (Fully Stitched)\n• Flair: 3.50 meter\n• (Attached Canvas )\n• Work: Embroidery Thread Work\n• Coluer: 2 two\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Occasion-ready skirt and blouse materials with artisan finishing",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.6,
    "reviewCount": 52,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 114,
    "name": "Palazzo Sets · product1 · Shivaanya Collection",
    "price": 1549,
    "originalPrice": 1691,
    "imageUrl": "/media/catalog/palazzo_sets/plazo-set-product1/img001.jpg",
    "videoUrl": "/media/catalog/palazzo_sets/plazo-set-product1/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/palazzo_sets/plazo-set-product1/img001.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img002.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img003.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img004.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img005.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img006.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img007.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img008.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img009.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img010.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img011.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img012.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img013.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img014.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product1/img015.jpg"
    ],
    "categoryName": "Palazzo Sets",
    "description": "• Heavenly Handmade Kurta Sharara Plazzo Set With Charkhi Gota Work\n• Short Kurta Details\n• Fabric: Best Soft Crunchy Chiffon Fabric With Beautiful Hand Charkhi Gota Patti Work\n• Length: 30–32 Inch\n• Sharara Plazzo Details\n• Fabric: Soft Crunchy Chiffon With Full Flared Pattern & Beautiful Gota Touch-Up (39–40 Inch)\n• Dupatta Details\n• Fabric: Soft Crunchy Chiffon With Beautiful Hand Charkhi Gota Work (2.1 Meter)\n• Weight: 700gm\n• 🏻 Book-Fast 🏻\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Soft flowing suit fabric with ornate accents",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.6,
    "reviewCount": 177,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 115,
    "name": "Palazzo Sets · product2 · Shivaanya Collection",
    "price": 1400,
    "originalPrice": 1533,
    "imageUrl": "/media/catalog/palazzo_sets/plazo-set-product2/img001.jpg",
    "videoUrl": "/media/catalog/palazzo_sets/plazo-set-product2/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/palazzo_sets/plazo-set-product2/img001.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img002.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img003.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img004.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img005.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img006.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img007.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img008.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img009.jpg",
      "/media/catalog/palazzo_sets/plazo-set-product2/img010.jpg"
    ],
    "categoryName": "Palazzo Sets",
    "description": "• Febrics Tyep\n• Febrics Faux Georgette Heavy Quality With Faux. Georgette umbrella Palzzo Full Flair\n• Duptta Faux Georgette\n• Gotta patti Lace Boder\n• Type: Kurti Cutwork\n• Kurti: Faux Georgette Heavy Quality And Gotta Patti Work Fancy Broket Pach Butt Cut Work\n• Kuri: Length 32-33 In\n• Kurti inner: American Heavy Butter Cotton\n• Sleeves: Broket Pach Butt Cut Work\n• Palazzo -: Faux Georgette, Gotta patti Lace Boder And Fully Heavy Flair\n• BE AWARE COPY FABRIC mbl\n• Size: S-36,M-38,L-40, XL-42, + XXL-44 Marzin\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Soft flowing suit fabric with ornate accents",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "S",
      "M",
      "L",
      "XL",
      "XXL"
    ],
    "rating": 4.8,
    "reviewCount": 98,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": true
  },
  {
    "id": 116,
    "name": "Code 1238 · Sarees · Shivaanya Collection",
    "price": 1699,
    "originalPrice": 1850,
    "imageUrl": "/media/catalog/sarees/sarees-code-1238-price-1699-20260318t200615z-1-001-code-1238-price-1699/img001.jpeg",
    "videoUrl": "/media/catalog/sarees/sarees-code-1238-price-1699-20260318t200615z-1-001-code-1238-price-1699/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-code-1238-price-1699-20260318t200615z-1-001-code-1238-price-1699/img001.jpeg",
      "/media/catalog/sarees/sarees-code-1238-price-1699-20260318t200615z-1-001-code-1238-price-1699/img002.jpeg",
      "/media/catalog/sarees/sarees-code-1238-price-1699-20260318t200615z-1-001-code-1238-price-1699/img003.jpeg"
    ],
    "categoryName": "Sarees",
    "description": "• Pure Diamond Chiffon Multi Tie & Dye Saree With Hand Charkhi Gota Work\n• Fabric: Pure Diamond Chiffon Fabric With Beautiful Hand Tie & Dye Multi Dyeing\n• Work: Traditional Hand Charkhi Gota Work On Full Saree With Trending Sabhyasachi Lace Border (5.5 Meter)\n• Fabric: Contrast Blouse With Beautiful Gota Work\n• Weight: Approx 600gm\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "Rani",
      "Tota",
      "Yellow"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.6,
    "reviewCount": 255,
    "isNew": false,
    "isFeatured": true,
    "isBestseller": false,
    "colorImageIndices": [
      0,
      1,
      2
    ]
  },
  {
    "id": 117,
    "name": "Code 1236 · Sarees · Shivaanya Collection",
    "price": 1749,
    "originalPrice": 1903,
    "imageUrl": "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img001.jpg",
    "videoUrl": "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img001.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img002.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img003.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img004.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img005.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img006.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img007.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img008.jpeg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img009.jpg",
      "/media/catalog/sarees/sarees-code-1236-price-1749-20260318t200616z-1-001-code-1236-price-1749/img010.jpeg"
    ],
    "categoryName": "Sarees",
    "description": "• Moni Roy Wear Viral Aangi Blouse Saree With Hand Charkhi Gota Work\n• Fabric: Soft Fendy Satin With 2 Inch Self Design Attractive Lappa Border On Full Saree (5.5 Meter)\n• Fabric: Pure Soft Shimmer Fabric With Beautiful Hand Charkhi Gota Work & Self Design Gota Patta Touch-Up 🏻\n• Ready To Wear Stitched Blouse (Up To 42 Size)\n• Weight: Approx 700gm\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "Moni"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.7,
    "reviewCount": 206,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 118,
    "name": "Code 1232 · Sarees · Shivaanya Collection",
    "price": 1299,
    "originalPrice": 1426,
    "imageUrl": "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img001.jpeg",
    "videoUrl": "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img001.jpeg",
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img002.jpeg",
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img003.jpg",
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img004.jpeg",
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img005.jpeg",
      "/media/catalog/sarees/sarees-code-1232-price-1299-20260318t200619z-1-001-code-1232-price-1299/img006.jpeg"
    ],
    "categoryName": "Sarees",
    "description": "• Fabric: Pure CC Georgette Saree With Beautiful Maharani Jaal Gota Ribbon Work & Sabhyasachi Lace\n• Fabric: Pure CC Georgette Fabric With Beautiful Maharani Jaal Gota Ribbon Work & Sequence Work On Full Saree With Trending Sabhyasachi Lace Border (5.5 Meter)\n• Fabric: Mono Banglori Blouse With Same As Saree Work (Unstitched 80cm)\n• Weight: Approx 700gm\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "Baby Pink",
      "Cherry",
      "Rani",
      "Red",
      "Sky"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.5,
    "reviewCount": 187,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": true,
    "colorImageIndices": [
      0,
      1,
      3,
      4,
      5
    ]
  },
  {
    "id": 119,
    "name": "Code 1239 · Sarees · Shivaanya Collection",
    "price": 1699,
    "originalPrice": 1850,
    "imageUrl": "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img001.jpg",
    "images": [
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img001.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img002.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img003.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img004.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img005.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img006.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img007.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img008.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img009.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img010.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img011.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img012.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img013.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img014.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img015.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img016.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img017.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img018.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img019.jpg",
      "/media/catalog/sarees/sarees-code-1239-price-1699-20260318t200622z-1-001-code-1239-price-1699/img020.jpg"
    ],
    "categoryName": "Sarees",
    "description": "• Trending Aangi Blouse Chinon Saree With Beautiful Kachi Gota Hand Work\n• Fabric: Pure Chinon Fabric With sober Kachi Gota Hand Work & Fancy Lace Border On Full Saree (5.5 Meter)\n• Fabric: Pure Satin Aangi Blouse With Beautiful Kachi Gota Work (Fully Stitched Up To 40 Size)\n• Weight: Approx 800gm\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "Black",
      "Bottel Green",
      "Fanta",
      "Purple",
      "Rani",
      "Red",
      "Royal Blue",
      "White",
      "Wine",
      "Yellow"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.6,
    "reviewCount": 233,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false,
    "colorImageIndices": [
      1,
      3,
      6,
      8,
      10,
      11,
      13,
      15,
      17,
      19
    ]
  },
  {
    "id": 120,
    "name": "Sarees · product1 · Shivaanya Collection",
    "price": 1699,
    "originalPrice": 1850,
    "imageUrl": "/media/catalog/sarees/sarees-product1/img001.jpg",
    "videoUrl": "/media/catalog/sarees/sarees-product1/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-product1/img001.jpg",
      "/media/catalog/sarees/sarees-product1/img002.jpg",
      "/media/catalog/sarees/sarees-product1/img003.jpg",
      "/media/catalog/sarees/sarees-product1/img004.jpg",
      "/media/catalog/sarees/sarees-product1/img005.jpg",
      "/media/catalog/sarees/sarees-product1/img006.jpg",
      "/media/catalog/sarees/sarees-product1/img007.jpg",
      "/media/catalog/sarees/sarees-product1/img008.jpg",
      "/media/catalog/sarees/sarees-product1/img009.jpg",
      "/media/catalog/sarees/sarees-product1/img010.jpg",
      "/media/catalog/sarees/sarees-product1/img011.jpg",
      "/media/catalog/sarees/sarees-product1/img012.jpg",
      "/media/catalog/sarees/sarees-product1/img013.jpg",
      "/media/catalog/sarees/sarees-product1/img014.jpg",
      "/media/catalog/sarees/sarees-product1/img015.jpg",
      "/media/catalog/sarees/sarees-product1/img016.jpg",
      "/media/catalog/sarees/sarees-product1/img017.jpg"
    ],
    "categoryName": "Sarees",
    "description": "• Fabric: Soft Pure marshmallow Shiny Chinnon Silk\n• Designer Ajarakh Print\n• Fancy Aari Zari Work With Real Mirror Work\n• Fancy Printed Blouse With Piping And Heavy Latkans\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.7,
    "reviewCount": 101,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 121,
    "name": "Sarees · product3 · Shivaanya Collection",
    "price": 1950,
    "originalPrice": 2116,
    "imageUrl": "/media/catalog/sarees/sarees-product3/img001.jpg",
    "videoUrl": "/media/catalog/sarees/sarees-product3/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-product3/img001.jpg",
      "/media/catalog/sarees/sarees-product3/img002.jpg",
      "/media/catalog/sarees/sarees-product3/img003.jpg",
      "/media/catalog/sarees/sarees-product3/img004.jpg",
      "/media/catalog/sarees/sarees-product3/img005.jpg",
      "/media/catalog/sarees/sarees-product3/img006.jpg",
      "/media/catalog/sarees/sarees-product3/img007.jpg",
      "/media/catalog/sarees/sarees-product3/img008.jpg"
    ],
    "categoryName": "Sarees",
    "description": "• Shivaanya Launching New Designer saree\n• Catalogue: Rinkal\n• Saree: Pure Fox Geogate With Beautiful Original Black Beeds Work with Cut work border\n• Blouse: Paired With Same Fabric Heavily Worked Fancy Blouse\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.7,
    "reviewCount": 203,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 122,
    "name": "Sarees · product4 · Shivaanya Collection",
    "price": 1775,
    "originalPrice": 1931,
    "imageUrl": "/media/catalog/sarees/sarees-product4/img001.jpg",
    "videoUrl": "/media/catalog/sarees/sarees-product4/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-product4/img001.jpg",
      "/media/catalog/sarees/sarees-product4/img002.jpg",
      "/media/catalog/sarees/sarees-product4/img003.jpg",
      "/media/catalog/sarees/sarees-product4/img004.jpg",
      "/media/catalog/sarees/sarees-product4/img005.jpg",
      "/media/catalog/sarees/sarees-product4/img006.jpg",
      "/media/catalog/sarees/sarees-product4/img007.jpg",
      "/media/catalog/sarees/sarees-product4/img008.jpg",
      "/media/catalog/sarees/sarees-product4/img009.jpg",
      "/media/catalog/sarees/sarees-product4/img010.jpg",
      "/media/catalog/sarees/sarees-product4/img011.jpg",
      "/media/catalog/sarees/sarees-product4/img012.jpg",
      "/media/catalog/sarees/sarees-product4/img013.jpg",
      "/media/catalog/sarees/sarees-product4/img014.jpg",
      "/media/catalog/sarees/sarees-product4/img015.jpg"
    ],
    "categoryName": "Sarees",
    "description": "• Shivaanya Launching New Designer saree\n• Catalog: Pooja\n• Available In 6 Colour Opation 🏼 🏼 🏼\n• Saree: PURE SOFT FANDY SATTIN SILK FABRIC ON BEAUTIFUL HAND WORK Fancy Lace Border IN SAREE\n• Blouse: PURE SOFT FANDY SATTIN SILK FABRIC ON ALL OVER HAND WORK ON BLOUSE\n• Note: BLOUSE STITCHED UP TO SIZE 42\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.5,
    "reviewCount": 226,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  },
  {
    "id": 123,
    "name": "Code 102 · Sarees · Shivaanya Collection",
    "price": 2049,
    "originalPrice": 2221,
    "imageUrl": "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img001.jpeg",
    "videoUrl": "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/vdo001.mp4",
    "videoObjectPosition": "center 38%",
    "videoBottomClipPct": 18,
    "images": [
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img001.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img002.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img003.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img004.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img005.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img006.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img007.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img008.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img009.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img010.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img011.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img012.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img013.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img014.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img015.jpeg",
      "/media/catalog/sarees/sarees-ram-102-price-2049-20260318t200838z-1-001-ram-102-price-2049/img016.jpeg"
    ],
    "categoryName": "Sarees",
    "description": "• Product code: Ram-102\n• Real modelling Product\n• Fabric: Pure Tissue silk\n• Work: Heavy Embroidery Sequence & thread Work\n• Inner: Micro Cotton\n• Size: M upto L margin\n• XL upto 2xl margin\n• (Fully Stitched)\n• Flair: 3.50 Meter\n• Attached Canvas and Cancan\n• (Full-Stitched)\n• Fabric: Pure bandhrej Georgette\n• Colour / finish may look slightly different on your screen — use carousel images as the guide for shade and motifs.",
    "fabric": "Designer drape fabrication with luxury finish",
    "colors": [
      "As shown"
    ],
    "sizes": [
      "Free Size (Saree)"
    ],
    "rating": 4.8,
    "reviewCount": 112,
    "isNew": false,
    "isFeatured": false,
    "isBestseller": false
  }
] as unknown as Product[];
